# Generated by Django 4.2 on 2025-10-28 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('tipo_Usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Veterinario', 'Veterinario'), ('Cliente', 'Cliente'), ('Recepcionista', 'Recepcionista')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('licencia_profesional', models.ImageField(upload_to='')),
                ('telefono', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarioex')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('Raza', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('hembra', 'hembra'), ('macho', 'macho')], max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('estado', models.BooleanField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento_prescrito', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=30)),
                ('costo_consulta', models.IntegerField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarioex')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarioex'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veterinario'),
        ),
    ]
